# Generated by Django 5.2.4 on 2025-08-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='phone',
            field=models.CharField(default=None, null=True),
        ),
    ]
