# Generated by Django 5.2.4 on 2025-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_master_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'verbose_name'},
        ),
        migrations.AddField(
            model_name='master',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='master',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='master',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='master',
            name='middle_name',
            field=models.CharField(blank=True, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone',
            field=models.CharField(default='00000000000', max_length=20, verbose_name='Телефон'),
        ),
    ]
