# Generated by Django 5.2.4 on 2025-08-06 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_master_options_master_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(default='00000000000', max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коммент')),
                ('master', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.master', verbose_name='Мастер')),
            ],
        ),
    ]
