# Generated by Django 5.2.4 on 2025-08-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_master_options_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='master',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
