# Generated by Django 5.2.4 on 2025-08-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved', 'Подтверждён'), ('completed', 'Выполнена'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
