# Generated by Django 5.2.4 on 2025-08-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='review',
            name='ai_checked_status',
            field=models.CharField(choices=[('ai_checked_true', 'Проверено ИИ'), ('ai_cancelled', 'Отменено ИИ'), ('ai_checked_in_progress', 'В процессе проверки'), ('ai_checked_false', 'Не проверено')], default='ai_checked_false', max_length=30, verbose_name='Статус ИИ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
